### ISSUE TITLE
False report with PEP 484 type comment

### ISSUE THREAD

**Issue by hongquan** [asmeurer/pytest-flakes#25] opened 2019-12-20 13:18 UTC
If a code has PEP 484 [type comment](https://www.python.org/dev/peps/pep-0484/#type-comments)

```py
from mod import SomeClass

a = b.get()   # type: SomeClass
```

pytest-flakes will mistakenly report that `SomeClass` is import but not used.

This report is not shown if running standalone `pyflakes`.

`pyflakes` explicitly says that it [supports](https://github.com/PyCQA/pyflakes/blob/master/NEWS.rst) this case:

> Mark names used in PEP 484 # type: ... comments as used

**Comment by fschulze** [comment] 2019-12-20 13:29
I'm not working on pytest-flakes anymore, I switched to pytest-flake8 myself.
I should update the readme etc.

**Comment by asmeurer** [comment] 2020-07-02 21:02
It would be useful to show the configuration options to get pyflakes-only errors from pytest-flake8 (no style warnings). This doesn't seem to be documented anywhere.

**Comment by fschulze** [comment] 2020-07-03 06:21
@asmeurer I use flake8 in code bases with very little pep8 compliance and even there the list of ignored warnings is only about 30. Not sure flake8 can be told to only do pyflakes checking.

If you are interested, I can transfer pytest-flakes for further maintenance.

**Comment by asmeurer** [comment] 2020-07-03 19:17
Raw flake8 can with `--select=F`. But it isn't clear if that is supported by pytest-flake8.

But I wouldn't mind helping continue to maintain this package if you cannot do it, as I generally prefer to just use pyflakes instead of flake8. Apparently I have contributed to this package before (I vaguely remember that).

**Comment by fschulze** [comment] 2020-07-04 05:43
@asmeurer You did #17. I'd be happy to add you on PyPI and transfer this repository to your GitHub Account. Another possibility would be the pytest organization if you would maintain it there, but they prefer multiple maintainers before transfer: https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#submitting-plugins-to-pytest-dev

**Comment by asmeurer** [comment] 2020-07-06 19:54
OK, that works for me. My PyPI username is `Aaron.Meurer`. I'm also fine with moving it to pytest but it sounds like we would need to find someone else willing to maintain it as well. I suspect there isn't too much maintenance work required for this project, since it mostly works, but I do use it and I would like to make sure it continues to work.

**Comment by asmeurer** [comment] 2020-07-06 19:56
By the way, regarding this issue @hongquan, I wasn't able to reproduce it. A possible cause is that your `pyflakes` and `pytest` commands are running from different Pythons, which have different versions of pyflakes installed. You can test with `python -m pyflakes` and `python -m pytest` to make sure you use the same one. I believe several issues relating to type hints were fixed in recent versions of pyflakes, so it is possible your pyflakes is just out of date in the Python that you run pytest with.

**Comment by hongquan** [comment] 2020-07-08 03:17
Thanks @asmeurer . That may be the case. I will check.

**Closed** 2020-08-26 07:40 UTC
